   CREATE TABLE "SYSTEM"."ROBOS" 
   (	"DOCUMENTO" NUMBER(12,0) NOT NULL ENABLE, 
	"FECHA" DATE, 
	"DEPARTAMENTO" VARCHAR2(255 BYTE), 
	"MUNICIPIO" VARCHAR2(255 BYTE), 
	"DIA" VARCHAR2(255 BYTE), 
	"HORA" TIMESTAMP (6), 
	"SITIO" VARCHAR2(255 BYTE), 
	"AGRESOR" VARCHAR2(255 BYTE), 
	"VICTIMA" VARCHAR2(255 BYTE), 
	"EDAD" NUMBER, 
	"PAIS_NACIMIENTO" VARCHAR2(255 BYTE), 
	"CLASE_EMPLEADO" VARCHAR2(255 BYTE), 
	"PROFESION" VARCHAR2(255 BYTE), 
	"ESCOLARIDAD" VARCHAR2(255 BYTE), 
	"CODIGO_DANE" NUMBER, 
	 CONSTRAINT "ROBOS_PK" PRIMARY KEY ("DOCUMENTO")
;

